### ISSUE TITLE
Some experiement around a better Raw Content mode

### ISSUE THREAD

**Issue by dfeyer** [Flowpack/Flowpack.StructuredEditing#2]
For a current project we need to have a better Raw Content mode. I create this issue to follow my experiment, currently no code online. Need to refactor the project the make an decoupled package.

Currently Raw Content mode only works for ContentCollection, and need some love to be really usable with advanced node types. My current plan are to make it more "automatic", backed by a light configuration to render any node types, and even simple node property (text, image, ... you name it), based on what @dimaip did with the StructuredEditing

The current rendering of a content collection look like:

![neosstructuredediting](https://user-images.githubusercontent.com/221173/38869613-90f2a898-424b-11e8-8b33-a2075d04d637.png)

And a more advanced node type render like this:

![neosstructurededitinggroupedproperty](https://user-images.githubusercontent.com/221173/38869719-eb80b71e-424b-11e8-80af-93b281697bef.png)

**Comment by dfeyer** [comment]
![image](https://user-images.githubusercontent.com/221173/38937552-bfd468da-4323-11e8-9b63-c5676f22ae88.png)

Now the EditorEnveloppe is integrated, looks good

**Comment by dimaip** [comment]
@dfeyer maybe it makes sense to integrate those editors directly in the raw mode, without putting them into the dropdown?

**Comment by dfeyer** [comment]
> @dfeyer maybe it makes sense to integrate those editors directly in the raw mode, without putting them into the dropdown?

To not loose the message I post on slack earlier. I think it depend for the editor. An in this case, maybe replace the pencil button of the EditorEnveloppe, by the action button of the image editor is the way to go. Currently I focus on the prototype of the backend rendering of the Raw Content mode. When that part is done, we can experiment a bit more with custom Editor or more smart UX choices.

I want the Raw Content mode to be fully customized in term of rendering (style, inline help, ...) and the rendering should be full fusion. So I'm a bit against the direct rendering of our Editor inline for this reason. But I full agree the the current duplicate image is awkward

**Comment by dfeyer** [comment]
# Configuration of the rendering

We need a way to make the configuration of the Raw Content rendering easy. I'm currently experimenting with layout configuration in `Settings.yaml`. I use `Ttree.Writer` package as an experiment, so the configuration look like this:

```
Medialib.Core.Party:Document.Person:
  options:
    Ttree:Writer:
      layout:
        default:
          title:
            path: properties.title
          help:
            position: 'after title'
            path: Medialib.Core.Party:Help.Person
          biography:
            path: childNodes.biography
          image:
            path: childNodes.image
          main:
            path: childNodes.main
          birthDate:
            path: properties.birthDate
          birthPlace:
            path: properties.birthPlace
          deathDate:
            path: properties.deathDate
          deathPlace:
            path: properties.deathPlace
          nationality:
            path: properties.birthDate
```

## Requirements

- For each block of the RawContent we can render: a property, a child node or a custom Fusion prototype
- Reuse the configuration of the property/childNode
- Maybe in the future can override this configuration in the layout
- Can support multiple layout (currently only the default one). The idea in the future is to have for a single editing mode, multiple preset (like for a Person: Contact Information, Customer Detail, Internal Note, ....)
- Support Positionnal ordering to make it easy to extend
